StackVista/stackstate-agent-integrations

mysql/stackstate_checks/mysql/mysql.py, mysql/tests/test_mysql.py, postgres/stackstate_checks/postgres/postgres.py, postgres/tests/test_common.py, postgres/tests/test_unit.py, stackstate_checks_base/stackstate_checks/base/__init__.py, stackstate_checks_base/stackstate_checks/base/checks/__init__.py, stackstate_checks_base/stackstate_checks/base/checks/base.py, stackstate_checks_base/stackstate_checks/base/stubs/__init__.py, stackstate_checks_base/stackstate_checks/base/stubs/topology.py, stackstate_checks_base/stackstate_checks/stubs/topology.py, stackstate_checks_base/tests/test_agent_check.py, stackstate_checks_dev/stackstate_checks/dev/plugin/plugin.py
- Add topology bindings to base checks
- Add topology to mysql and postgres checks
=> Add topology

.gitignore, .setup-scripts/setup_env.sh, README.md, cloudera/setup.py, cloudera/stackstate_checks/__init__.py, cloudera/stackstate_checks/cloudera/__about__.py, cloudera/stackstate_checks/cloudera/__init__.py, cloudera/stackstate_checks/cloudera/cloudera.py, cloudera/stackstate_checks/cloudera/data/conf.yaml.example, cloudera/tests/conftest.py, cloudera/tests/test_cloudera.py, mysql/setup.py, stackstate_checks_dev/stackstate_checks/dev/tooling/commands/agent/__init__.py, stackstate_checks_dev/stackstate_checks/dev/tooling/create.py, stackstate_checks_dev/stackstate_checks/dev/tooling/templates/check/{check_name}/README.md
- improve readme
- fix cloudera config sample
- cleanup mysql setup
- branding
=> Improve experience

README.md, stackstate_checks_dev/stackstate_checks/dev/tooling/commands/env/check.py, stackstate_checks_dev/stackstate_checks/dev/tooling/e2e/agent.py, stackstate_checks_dev/stackstate_checks/dev/tooling/e2e/docker.py, stackstate_checks_dev/stackstate_checks/dev/tooling/e2e/local.py
enable logging when running the check within an env install requirements when updating a check within an env
=> Improve checksdev UX

.setup-scripts/load_deps.sh, agent_integration_sample/tox.ini, aws_xray/tox.ini, cloudera/tox.ini, kubelet/tox.ini, kubernetes_state/tox.ini, mysql/tox.ini, nagios/tox.ini, openmetrics/tox.ini, postgres/tox.ini, sap/tox.ini, scom/tox.ini, servicenow/tox.ini, stackstate_checks_base/tox.ini, stackstate_checks_dev/tox.ini, static_topology/tox.ini, vsphere/tox.ini, wmi_check/tox.ini, zabbix/tox.ini
=> Stac 0 fix pipeline

nagios/stackstate_checks/nagios/nagios.py, nagios/tests/compose/nagios4/localhost.cfg
https://stackstate.atlassian.net/browse/STAC-10614
Added tags data to event, and title and message
=> STAC-10614 added missing data to event

servicenow/stackstate_checks/servicenow/servicenow.py
=> Stac 10855 servicenow bug

vsphere/stackstate_checks/vsphere/vsphere.py
=> fix timeout and keep snapshots

nagios/stackstate_checks/nagios/nagios.py, nagios/tests/test_nagios.py
https://stackstate.atlassian.net/browse/STAC-10614
Tags data fixed so `event_state` has proper format.
=> Removed space that caused problems

servicenow/stackstate_checks/servicenow/data/conf.yaml.example, servicenow/stackstate_checks/servicenow/servicenow.py
https://stackstate.atlassian.net/browse/STAC-10855
Update default batch size.
=> added default batch size

nagios/stackstate_checks/nagios/nagios.py, nagios/tests/test_nagios.py
https://stackstate.atlassian.net/browse/STAC-11119
Sets right message title host and service event
=> Stac 11119 service name

vsphere/stackstate_checks/vsphere/vsphere.py, vsphere/tests/test_vsphere.py
=> Stac-11097 reconnect on unauthenticated exception

scom/stackstate_checks/scom/scom.py
=> send ok service check once successful

nagios/tests/test_nagios.py, stackstate_checks_base/stackstate_checks/base/__init__.py, stackstate_checks_base/stackstate_checks/base/checks/base.py, stackstate_checks_base/stackstate_checks/base/utils/common.py, stackstate_checks_base/stackstate_checks/base/utils/tailfile.py, stackstate_checks_base/stackstate_checks/utils/type_debugging.py, stackstate_checks_base/tests/test_agent_check.py, stackstate_checks_base/tests/test_encoding.py, stackstate_checks_base/tox.ini
https://stackstate.atlassian.net/browse/STAC-11298
Unicode fix for all strings that are send to go python bindings.
=> STAC-11298 agent base unicode fix for go bindings

.gitignore, nagios/stackstate_checks/nagios/nagios.py, nagios/tests/test_nagios.py, stackstate_checks_base/stackstate_checks/base/__init__.py, stackstate_checks_base/stackstate_checks/base/checks/base.py, stackstate_checks_base/stackstate_checks/base/utils/persistent_state.py, stackstate_checks_base/stackstate_checks/base/utils/telemetry.py, stackstate_checks_base/stackstate_checks/utils/persistent_state.py, stackstate_checks_base/tests/test_agent_check.py, stackstate_checks_base/tests/test_utils.py, stackstate_checks_dev/stackstate_checks/dev/plugin/plugin.py
=> add persistent state for integrations

stackstate_checks_base/stackstate_checks/base/checks/base.py, stackstate_checks_base/stackstate_checks/base/utils/persistent_state.py, stackstate_checks_base/tests/test_agent_check.py
https://stackstate.atlassian.net/browse/STAC-10665
Fixes for filename and datetime type when persisting state
=> Stac 10665 persistent state fix

servicenow/stackstate_checks/servicenow/servicenow.py
https://stackstate.atlassian.net/browse/STAC-11363
Using `json.load` instead `yaml.safe_load`
=> use json load now

.gitlab-ci.yml
=> gitlab needs

servicenow/stackstate_checks/servicenow/servicenow.py, servicenow/tests/samples/CHG0000001.json, servicenow/tests/samples/CHG0000002.json, servicenow/tests/test_servicenow.py
https://stackstate.atlassian.net/browse/STAC-11357
`str.format` causes unicode problems in py2 so we are switching to `%` operator for string concatenation
=> Stac 11357 snow remove str.format it causes py2 utf-8 encoding problems

stackstate_checks_base/stackstate_checks/base/checks/base.py, stackstate_checks_base/tests/test_agent_check.py
=> dynamic identifier support

vsphere/stackstate_checks/vsphere/vsphere.py, vsphere/tests/test_vsphere.py
=> Stac 11313 vsphere metric query limit

servicenow/stackstate_checks/servicenow/servicenow.py, servicenow/tests/test_servicenow.py, stackstate_checks_base/stackstate_checks/base/__init__.py, stackstate_checks_base/stackstate_checks/base/checks/__init__.py, stackstate_checks_base/stackstate_checks/base/checks/base.py, stackstate_checks_base/stackstate_checks/base/stubs/topology.py, stackstate_checks_base/stackstate_checks/base/utils/agent_integration_test_util.py, stackstate_checks_base/tests/test_agent_check.py
=> default integration instance for instance key

zabbix/stackstate_checks/zabbix/zabbix.py, zabbix/tests/test_zabbix.py
=> use json load

zabbix/stackstate_checks/zabbix/zabbix.py, zabbix/tests/test_zabbix.py
=> move stop snapshot from finally block and use StackPackInstance

servicenow/stackstate_checks/servicenow/data/conf.yaml.example, servicenow/stackstate_checks/servicenow/servicenow.py, servicenow/tests/test_servicenow.py
=> stac-10915 servicenow tags

agent_integration_sample/tests/expected/expected_topology_instance.json, agent_integration_sample/tests/expected/expected_topology_instance_topology_config.json, servicenow/servicenow.d/instance.servicenow_cmdb.https_instance.service_now.com.state, servicenow/tests/test_servicenow.py, stackstate-changelog.md, stackstate_checks_base/stackstate_checks/base/checks/base.py, stackstate_checks_base/tests/test_agent_check.py
https://stackstate.atlassian.net/secure/RapidBoard.jspa?rapidView=98&projectKey=STAC&modal=detail&selectedIssue=STAC-11132
- Remove Stackstate tags from the tags object after it has been successfully mapped into the data object
=> STAC-11132-Common-stackstate-tags-handling

agent_integration_sample/tests/expected/expected_topology_instance.json, agent_integration_sample/tests/expected/expected_topology_instance_topology_config.json, servicenow/servicenow.d/instance.servicenow_cmdb.https_instance.service_now.com.state, servicenow/tests/test_servicenow.py, stackstate-changelog.md, stackstate_checks_base/stackstate_checks/base/checks/base.py, stackstate_checks_base/tests/test_agent_check.py
Reverts StackVista/stackstate-agent-integrations#112
=> Revert "STAC-11132-Common-stackstate-tags-handling"

stackstate-changelog.md
https://stackstate.atlassian.net/browse/STAC-12336
Changelog entry
=> Added changelog entry I forgot to add with STAC-12336

stackstate-changelog.md
=> add changelog updates for state location config

aws_xray/stackstate_checks/aws_xray/aws_xray.py, aws_xray/tests/test_aws.py
=> aws x-ray fixes

stackstate-changelog.md
=> updated changelog

stackstate_checks_base/stackstate_checks/base/checks/base.py
https://stackstate.atlassian.net/browse/STAC-12265
logs
=> adds log warnings if stub APIs are used

aws_topology/tests/cloudformation_infra/base.cfn.yaml, aws_topology/tests/cloudformation_infra/main-account-main-region.cfn.yaml, aws_topology/tests/cloudformation_infra/main-account-secondary-region.cfn.yaml
https://stackstate.atlassian.net/browse/STAC-12856
Add a set of CloudFormation templates in aws_topology to create a dummy AWS infrastructure to run integration tests against.
=> Stac 12856 cloudformation templates

.gitlab-ci.yml, aws_topology/stackstate_checks/aws_topology/resources/api_gateway.py, aws_topology/stackstate_checks/aws_topology/resources/sqs.py, aws_topology/stackstate_checks/aws_topology/resources/stepfunction.py, aws_topology/tests/cloudformation_infra/notification-send/src/index.py, aws_topology/tests/json/template/test_describe_cloudformation_stack_resources.json, aws_topology/tests/json/template/test_sqs_list_queues.json, aws_topology/tests/test_cloudtrail.py, aws_topology/tests/test_template.py, aws_topology/tox.ini
https://stackstate.atlassian.net/browse/STAC-13125
Add aws_topology to the gitlab-ci.yaml, and fix some cross-region/cross-account errors for SQS and API Gateway from #145 that got merged into master unnoticed as the pipeline didn't run the tests.
=> Stac 13125 aws ci

aws_topology/stackstate_checks/aws_topology/aws_topology.py, aws_topology/stackstate_checks/aws_topology/resources/api_gateway.py, aws_topology/stackstate_checks/aws_topology/resources/autoscaling.py, aws_topology/stackstate_checks/aws_topology/resources/cloudformation.py, aws_topology/stackstate_checks/aws_topology/resources/dynamodb.py, aws_topology/stackstate_checks/aws_topology/resources/ec2.py, aws_topology/stackstate_checks/aws_topology/resources/ecs.py, aws_topology/stackstate_checks/aws_topology/resources/elb_classic.py, aws_topology/stackstate_checks/aws_topology/resources/elb_v2.py, aws_topology/stackstate_checks/aws_topology/resources/firehose.py, aws_topology/stackstate_checks/aws_topology/resources/lambdaf.py, aws_topology/stackstate_checks/aws_topology/resources/rds.py, aws_topology/stackstate_checks/aws_topology/resources/redshift.py, aws_topology/stackstate_checks/aws_topology/resources/registry.py, aws_topology/stackstate_checks/aws_topology/resources/s3.py, aws_topology/stackstate_checks/aws_topology/resources/sns.py, aws_topology/stackstate_checks/aws_topology/resources/stepfunction.py, aws_topology/stackstate_checks/aws_topology/utils.py, aws_topology/tests/test_stepfunctions.py
https://stackstate.atlassian.net/browse/STAC-13148
https://stackstate.atlassian.net/browse/STAC-13157
locking introduced
+ emit_relation
+ location has become a schematic
=> STAC-13148 STAC-13157 error->thread lock + location->Schematics  + emit_relation

aws_topology/stackstate_checks/aws_topology/resources/dynamodb.py
https://stackstate.atlassian.net/browse/STAC-13186
Improve handling in DynamoDB, make it match with new resource format
Additions:
- Schematics validation for API calls
- Error handling on no permission (show the user missing IAM permissions)
- Formatting fixes
=> Refactor and add permission checks to DynamoDB

stackstate_checks_base/requirements-dev.txt, stackstate_checks_base/requirements.in, stackstate_checks_base/stackstate_checks/base/data/agent_requirements.in, stackstate_checks_base/tests/test_ddyaml.py
=> STAC-13196 v3 python2

aws_topology/stackstate_checks/aws_topology/resources/elb_classic.py
https://stackstate.atlassian.net/browse/STAC-13276
- If there are no load balancers returned, do not attempt to process them.
=> Fix STAC-13276 tag collection failure

aws_topology/stackstate_checks/aws_topology/resources/autoscaling.py, aws_topology/stackstate_checks/aws_topology/resources/dynamodb.py, aws_topology/tests/test_autoscaling.py, aws_topology/tests/test_dynamodb.py
None
- Rename DynamoDB and Autoscaling components to have friendlier names
- Fix tests with new names
=> Change Autoscaling & DynamoDB names

aws_topology/stackstate_checks/aws_topology/resources/lambdaf.py
https://stackstate.atlassian.net/browse/STAC-13265
- Refactor lambda code
- Add IAM permissions checks
- Attempt to return a minimal component if get_function fails
- Add Schematics validation
=> Refactor Lambda

splunk_base/stackstate_checks/splunk/client/splunk_client.py, splunk_base/stackstate_checks/splunk/config/__init__.py, splunk_base/stackstate_checks/splunk/config/splunk_instance_config.py, splunk_base/tests/test_splunk_client.py, splunk_topology/requirements.in, splunk_topology/stackstate_checks/splunk_topology/splunk_topology.py, splunk_topology/tests/conftest.py, splunk_topology/tests/test_unit.py
- Push authentication into the splunk client
- Plug leaky abstraction regarding authentication
- Drop instance distinction for state management (agent v2 does not need that)
=> Stac 13174: simplify auth

splunk_base/setup.py, splunk_base/stackstate_checks/splunk/client/splunk_client.py, splunk_base/stackstate_checks/splunk/config/__init__.py, splunk_base/stackstate_checks/splunk/config/splunk_instance_config.py, splunk_base/stackstate_checks/splunk/saved_search_helper/__init__.py, splunk_base/stackstate_checks/splunk/saved_search_helper/saved_search_helper.py, splunk_base/tests/test_saved_search_helper.py, splunk_base/tests/test_splunk_client.py, splunk_base/tests/test_splunk_instance_config.py, splunk_topology/stackstate_checks/splunk_topology/splunk_topology.py, splunk_topology/tests/test_unit.py
- Extract saved search helper from splunk topology, preparing for the splunk health
- 
=> Stac 13174: Extract saved search helper

aws_topology/stackstate_checks/aws_topology/resources/ec2.py, aws_topology/tests/conftest.py, aws_topology/tests/json/ec2/cloudtrail/state_pending.json, aws_topology/tests/json/ec2/cloudtrail/state_running.json, aws_topology/tests/json/ec2/cloudtrail/state_stopped.json, aws_topology/tests/json/ec2/cloudtrail/state_stopping.json, aws_topology/tests/json/ec2/cloudtrail/state_terminated.json, aws_topology/tests/test_ec2.py
https://stackstate.atlassian.net/browse/STAC-13315
=> STAC-13315 Handling of the EC2 state EventBridge events

aws_topology/stackstate_checks/aws_topology/resources/__init__.py, aws_topology/stackstate_checks/aws_topology/resources/ecs.py, aws_topology/stackstate_checks/aws_topology/resources/service_discovery.py, aws_topology/tests/cloudformation_infra/main-account-main-region.cfn.yaml, aws_topology/tests/json/servicediscovery/get_namespace_ed667bc.json, aws_topology/tests/json/servicediscovery/get_service_ade34df.json, aws_topology/tests/json/servicediscovery/get_service_d25031e.json, aws_topology/tests/json/servicediscovery/list_instances_5f9eba9.json, aws_topology/tests/json/servicediscovery/list_instances_70cf1e2.json, aws_topology/tests/json/servicediscovery/list_services_1e04b4c.json, aws_topology/tests/test_service_discovery.py
https://stackstate.atlassian.net/browse/STAC-13326
- Refactor ECS
- Add Schematics
- Add IAM permission checks
- Fix query pagination to handle more than 100 resources
- Use Task UUID for task name if Task Definition Name is not available
- Split Service Discovery into its own API file
- Add tests for Service Discovery
- Increase Service Discovery relations - EC2 and all ECS tasks will be related to their hosted zone
- Add Service Discovery components to integration tests
=> Stac 13326 ecs refactor

aws_topology/stackstate_checks/aws_topology/resources/redshift.py, aws_topology/tests/json/redshift/describe_tags_a7a323d.json
https://stackstate.atlassian.net/browse/STAC-13455
- Fix API error where cluster type and ARN were being specified at the same time
- Optimise tag collection - fetch all tags in a paginated call, then find associated tags after
=> Fix STAC-13455 tag API call returns error

aws_topology/stackstate_checks/aws_topology/resources/elb_classic.py, aws_topology/stackstate_checks/aws_topology/resources/elb_v2.py, aws_topology/tests/json/elbv2/cloudtrail/create_listener.json, aws_topology/tests/json/elbv2/cloudtrail/create_loadbalancer.json, aws_topology/tests/json/elbv2/cloudtrail/create_target_group.json, aws_topology/tests/json/elbv2/cloudtrail/delete_loadbalancer.json, aws_topology/tests/json/elbv2/cloudtrail/delete_target_group.json, aws_topology/tests/json/elbv2/describe_load_balancers_60dd265.json, aws_topology/tests/json/elbv2/describe_tags_77c93a3.json, aws_topology/tests/json/elbv2/describe_target_groups_c9728d1.json, aws_topology/tests/json/elbv2/describe_target_health_2060118.json, aws_topology/tests/test_elbv2.py
https://stackstate.atlassian.net/browse/STAC-13413
- Refactor ELBv2
- Implement Schematics
- Add IAM permissions checks
- Fetch tags for target groups
- Paginate tag calls
- When updating one target group, also update the associated load balancer
- 
=> ELBv2 Refactor + Improvements

aws_topology/stackstate_checks/aws_topology/resources/sqs.py, aws_topology/stackstate_checks/aws_topology/resources/utils.py, aws_topology/tests/conftest.py
https://stackstate.atlassian.net/browse/STAC-13497
- Support all SQS URL types that SQS can support
- Fixes issue where regular expression matching fails when IAM permission `sqs:GetQueueAttributes` is removed. This API call always returns a same-format SQS URL, but `sqs:ListQueues` can be different
- Fix uncaught AuthorizationError
=> Add all SQS URL combinations

aws_topology/stackstate_checks/aws_topology/resources/elb_classic.py, aws_topology/stackstate_checks/aws_topology/resources/elb_v2.py
https://stackstate.atlassian.net/browse/STAC-13502
- Fix issue where an unhandled API error would occur if permission `elasticloadbalancing:DescribeLoadBalancers` is removed
- Fix issue where a NoneType error would occur if permission `elasticloadbalancing:DescribeTags` is removed
=> Fix ELB reduced permission cases

aws_topology/stackstate_checks/aws_topology/resources/dynamodb.py, aws_topology/tests/json/dynamodb/list_tags_of_resource_01b54fd.json, aws_topology/tests/json/dynamodb/list_tags_of_resource_1daae44.json, aws_topology/tests/json/dynamodb/list_tags_of_resource_750c086.json, aws_topology/tests/json/dynamodb/list_tags_of_resource_d446478.json
https://stackstate.atlassian.net/browse/STAC-13511
- Fix DynamoDB description construction when `dynamodb:DescribeTable` is missing
- Fix tag collection
- Add tag collection API response tests
=> Fix DynamoDB tag and description collection with reduced perms

aws_topology/stackstate_checks/aws_topology/resources/lambdaf.py, aws_topology/tests/json/lambda/list_functions_9863bd9.json, aws_topology/tests/test_lambda.py
https://stackstate.atlassian.net/browse/STAC-13514
- If an RDS URI is found in the environment variables of a lambda function, make a relation
- Add tests to check URI matching
=> Create lambda -> RDS relation

aws_topology/stackstate_checks/aws_topology/resources/api_gateway.py, aws_topology/stackstate_checks/aws_topology/resources/cloudformation.py, aws_topology/stackstate_checks/aws_topology/resources/dynamodb.py, aws_topology/stackstate_checks/aws_topology/resources/firehose.py, aws_topology/stackstate_checks/aws_topology/resources/kinesis.py, aws_topology/stackstate_checks/aws_topology/resources/lambdaf.py, aws_topology/stackstate_checks/aws_topology/resources/route53_domain.py, aws_topology/stackstate_checks/aws_topology/resources/route53_hostedzone.py, aws_topology/stackstate_checks/aws_topology/resources/s3.py, aws_topology/stackstate_checks/aws_topology/resources/service_discovery.py, aws_topology/stackstate_checks/aws_topology/resources/sns.py, aws_topology/stackstate_checks/aws_topology/resources/sqs.py, aws_topology/stackstate_checks/aws_topology/resources/stepfunction.py
https://stackstate.atlassian.net/browse/STAC-13524 (issue is not fully resolved here, only improved)
- Fix issue where the paginator was fetching all pages first before sending out items. This defeated the purpose of the paginator. Now new pages are fetched only when the previous page has been exhausted.
=> Fix list item pagination

splunk_base/setup.py
=> stac-13564: fix import issue with splunk base

aws_topology/stackstate_checks/aws_topology/resources/rds.py, aws_topology/tests/test_rds.py
https://stackstate.atlassian.net/browse/STAC-13576
Made schematics for instance endpoint not mandatory
Added Endpoint / ReaderEndpoint processing to the cluster
Fix incorrect value used for Cluster Name
=> endpoint fixes rds for aurora

stackstate-changelog.md
=> updated changelog for 1.14.0

zabbix/stackstate_checks/zabbix/zabbix.py, zabbix/tests/test_zabbix.py
=> stac-7258: add instance url  as identifier

aws_topology/tests/cloudformation_infra/helloworld-serverless.yaml, aws_topology/tests/cloudformation_infra/main-account-main-region.cfn.yaml, aws_topology/tests/cloudformation_infra/sqs-poll.py
- Fix NotificationEc2 psycopg2 installation
- Run a SELECT every 5 seconds to create more VPC traffic 
- Add Aurora Serverless to the integrations Cfn template
=> Update CloudFormation integration tests

aws_topology/stackstate_checks/aws_topology/data/conf.yaml.example
=> stac-13663: update default min_collection_interval to 120

solarwinds/.gitignore, solarwinds/stackstate_checks/solarwinds/solarwinds.py, solarwinds/tests/samples/npm_and_udt_topology_dumps.json, solarwinds/tests/samples/npm_topology_dumps.json
https://stackstate.atlassian.net/browse/STAC-13796
Fixed network_host identifier
=> STAC-13796 Solarwinds Component has multiple health statuses

stackstate-changelog.md
=> Added release notes for 1.15.0

dynatrace/stackstate_checks/dynatrace/dynatrace.py, dynatrace/tests/samples/expected_host_topology.json, dynatrace/tests/samples/expected_smartscape_full_topology.json, dynatrace/tests/samples/host_response.json
=> fix attribute type and tests

solarwinds/stackstate_checks/solarwinds/solarwinds.py, solarwinds/tests/test_solarwinds.py, stackstate-changelog.md
https://stackstate.atlassian.net/browse/STAC-14057
Create interface components with MAC address and no IP address
=> STAC-14057 Create interface components with MAC address and no IP address

zabbix/stackstate_checks/zabbix/zabbix.py, zabbix/tests/test_zabbix.py
=> stac-13984: support common tag and add tests

zabbix/stackstate_checks/zabbix/zabbix.py, zabbix/tests/test_zabbix.py
=> STAC-13977 Fix Zabbix identifiers

stackstate_checks_base/stackstate_checks/base/data/agent_requirements.in, vsphere/requirements.in
https://stackstate.atlassian.net/browse/STAC-14233
We packaged new version of vmware vSphere SDK to artifactory
=> STAC-14233 vsphere libray fix

.gitignore, aws_topology/stackstate_checks/aws_topology/data/conf.yaml.example, aws_topology/stackstate_checks/aws_topology/resources/sqs.py, aws_topology/stackstate_checks/aws_topology/resources/stepfunction.py, aws_topology/tests/json/stepfunctions/describe_state_machine_f72336d.json, aws_topology/tests/json/stepfunctions/list_state_machines_f1b9590.json, aws_topology/tests/json/stepfunctions/list_tags_for_resource_fa0eb5b.json, aws_topology/tests/test_all_apis.py, aws_topology/tests/test_stepfunctions.py, stackstate-changelog.md
https://stackstate.atlassian.net/browse/STAC-14622
=> STAC-14622 fix for error in StepFunction definiton

stackstate-changelog.md
https://stackstate.atlassian.net/jira/software/c/projects/STAC/boards/98?modal=detail&selectedIssue=STAC-12434&search=raw
Add support for Raw Metrics in line with the current v2/v3 api format
=> Raw Metric Changelog Update

stackstate-changelog.md, stackstate_checks_base/stackstate_checks/base/data/agent_requirements.in
=> STAC-0123 fix broken py3 dependency.

aws_topology/stackstate_checks/aws_topology/resources/lambdaf.py, aws_topology/tests/json/lambda/list_event_source_mappings_a0eaff0.json, aws_topology/tests/test_lambda.py, stackstate-changelog.md
https://stackstate.atlassian.net/browse/STAC-15905
Swap the relation direction for SQS and Lambda
=> Open Telemetry

stackstate-changelog.md
https://stackstate.atlassian.net/browse/STAC-14816
Fixed date on changelog file for version 1.19.0
=> STAC-14816 changelog date fix

stackstate-changelog.md, vsphere/stackstate_checks/vsphere/data/conf.yaml.example, vsphere/stackstate_checks/vsphere/vsphere.py, vsphere/tox.ini
https://stackstate.atlassian.net/browse/STAC-14671
- vSphere config example update
- tox.ini fix for compiling openssl on mac
=> STAC-14671 vSphere collection_level

README.md, dynatrace_topology/stackstate_checks/dynatrace_topology/dynatrace_topology.py, dynatrace_topology/tests/samples/application_response.json, dynatrace_topology/tests/samples/expected_application_topology.json, dynatrace_topology/tests/samples/expected_smartscape_full_topology.json, dynatrace_topology/tests/samples/expected_synthetic_monitoring_topology.json, dynatrace_topology/tests/samples/sythetic_monitoring_response.json, dynatrace_topology/tests/test_dynatrace_synthetic_monitors.py, dynatrace_topology/tests/test_dynatrace_topology.py, stackstate-changelog.md
https://stackstate.atlassian.net/browse/STAC-16372
https://stackstate.atlassian.net/browse/STAC-16597
- Added new unit tests to check relation between applications and synthetic monitors
- Updated unit tests for different types of synthetic monitors
- Fixed a bug where application and synthetic monitor relations where inverted
- Refactored _collect_relations to remove duplicate code
=> Stac 16372 dynatrace topology tests

stackstate_checks_dev/tests/test_conditions.py
=> Fix for checksdev failing test

.gitlab-ci.yml
=> STAC-18511 Remove windows jobs (make manual).

aws_topology/tests/test_aws_client.py, stackstate_checks_base/tests/test_openmetrics.py, stackstate_checks_base/tests/test_prometheus.py
=> STAC-19574: also collect metric without a type

.gitlab-ci.yml, .setup-scripts/image/Dockerfile, .setup-scripts/image/Makefile
=> STAC-19729 Build new docker image.

.gitlab-ci.yml
=> STAC-19729 Switch to master image.

openmetrics/stackstate_checks/openmetrics/data/conf.yaml.example, openmetrics/tests/test_openmetrics.py, stackstate_checks_base/stackstate_checks/base/checks/openmetrics/mixins.py, stackstate_checks_base/stackstate_checks/base/checks/prometheus/base_check.py, stackstate_checks_base/tests/test_prometheus.py
https://stackstate.atlassian.net/browse/STAC-19887
=> STAC-19887 OpenMetrics agent check should send counter values as-is

.setup-scripts/setup_env.sh, openmetrics/tests/test_openmetrics.py, stackstate_checks_base/stackstate_checks/base/checks/openmetrics/mixins.py, stackstate_checks_base/stackstate_checks/base/data/agent_requirements.in, stackstate_checks_dev/setup.py, stackstate_checks_dev/tests/docker/test_default.yaml, vsphere/requirements.in, vsphere/tox.ini
=> STAC-19602: don't rewrite openmetrics histogram

stackstate_checks_base/requirements.in, stackstate_checks_base/stackstate_checks/base/data/agent_requirements.in
=> STAC-20332 Undo explicit CVE fix.

splunk_base/stackstate_checks/splunk/client/splunk_client.py, splunk_base/stackstate_checks/splunk/saved_search_helper/saved_search_helper.py, splunk_base/tests/test_saved_search_helper.py
=> STAC-20328 Process changes from YMvanderHorst:fix-splunk-bugs

splunk_base/stackstate_checks/splunk/client/splunk_client.py, splunk_base/stackstate_checks/splunk/saved_search_helper/saved_search_helper.py, splunk_base/tests/test_saved_search_helper.py
=> STAC-20328 Update Splunk Topology check to allow for specifying a splunk app for saved searches.
